#ifndef VERSION_H
#define VERSION_H

#define TINKLINK_VERSION_MAJOR 1
#define TINKLINK_VERSION_MINOR 12
#define TINKLINK_VERSION_PATCH 0

#define TINKLINK_VERSION_STRING "1.12.0"

#endif // VERSION_H
