#ifndef VERSION_H
#define VERSION_H

#define TINKLINK_VERSION_MAJOR 1
#define TINKLINK_VERSION_MINOR 13
#define TINKLINK_VERSION_PATCH 0

#define TINKLINK_VERSION_STRING "1.13.0"

#endif // VERSION_H
